config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # devise_for :users, controllers: { registrations: 'profiles' }
  mount Sidekiq::Web => '/sidekiq'
  root to: "pages#home"
  devise_for :users
  resources :medications
  get '/notifications', to: 'notifications#index'
  delete '/notifications', to: 'notifications#destroy_all'




resources :notifications, only: [:destroy]

  # resources :reminders, only: [:index, :show, :edit, :update, :destroy] do
  #   member do
  #     patch :mark_as_taken
  #   end
  # end

  resources :intervals, only: [:index, :show, :create, :update, :destroy]
  resources :medication_frequencies, only: [:index, :show, :create, :update, :destroy]
  resource :profile, only: [:show]

  devise_scope :user do
    resources :sessions, only: [:destroy], path: 'users/sign_out', as: :destroy_user_session
  end






end

app/models/medication.rb
# app/models/medication.rb
class Medication < ApplicationRecord
  validates :name, presence: true
  validates :med_type, presence: true
  validates :quantity, presence: true
  validates :instruction, presence: true
  validates :frequency, presence: true
  validates :start_time, presence: true
  validates :interval, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  # validates :medication_frequency, presence: true
  # validates :medication_interval, presence: true
  has_many :medication_frequencies, dependent: :destroy
  accepts_nested_attributes_for :medication_frequencies
  belongs_to :interval
  belongs_to :user
  has_many :medication_frequencies, dependent: :destroy
  accepts_nested_attributes_for :medication_frequencies

  # after_create :schedule_medication_notification



  private

#   def schedule_medication_notification(user_id)
#     create_medication_notification("Medication successfully created: #{name}")
#   end
# end

  def create_medication_for_user(user, medication_params)
    user.medications.create(medication_params)
  end
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
  before_action :set_medication, only: [:show, :edit, :update, :destroy]

def index
  @user = current_user
  @notifications = @user.notifications.unread
  @notifications.update_all(read_at: Time.zone.now)
  @medication = Medication.all
  if @user
    case params[:filter]
    when 'today'
      @medications = @user.medications.where('start_date >= ? AND start_date <= ?', Time.zone.now.beginning_of_day, Time.zone.now.end_of_day)
      @date = Time.zone.now.strftime("%A, %B %d, %Y")
    when 'tomorrow'
      @medications = @user.medications.where('start_date >= ?', Time.zone.now.beginning_of_day + 1.day)
      @date = (Time.zone.now + 1.day).strftime("%A, %B %d, %Y")
    else
      @medications = @user.medications
      @date = nil
    end
  else
    redirect_to root_path, alert: 'You need to be logged in to access this page.'
  end
end

  def show
    @medications = Medication.where(user_id: current_user.id)
  end

  def new
    @notifications = Notification.unread
    @medication = Medication.new
    @medication.medication_frequencies.new
    @medications = Medication.where(user_id: current_user.id)
  end

  def create
    @medication = current_user.medications.build(medication_params)
    @medication.user = current_user
    @medication_duration = ((@medication.end_date - @medication.start_date).to_i) / 86400

    case @medication.frequency
    when "Once per day"
      @medication_quantity = @medication_duration * 1
    when "Twice per day"
      @medication_quantity = @medication_duration * 2
    when "Thrice per day"
      @medication_quantity = @medication_duration * 3
    end

    if @medication_duration === 1
      @medication_duration = "1 day"
    else
      @medication.duration = @medication_duration.to_s + " days"
    end


    @medication.interval = Interval.find(params[:medication][:interval_id])
    if @medication.save!
      message = "It's time to take your #{@medication.quantity} #{@medication.med_type} of #{@medication.name} #{@medication.instruction}, have a nice day!!"
      create_medication_notification(message)
      schedule_medication_notification(@medication, message)

      flash[:notice] = 'Medication successfully created'
      redirect_to medications_path
      NotificationBroadcastJob.schedule_medication_notification(@medication)
    else
      render :new
    end
  end




  def edit
    # @medication is already set by before_action
  end

  def update
    @medication.update(medication_params)
    redirect_to medications_path, notice: 'Medication successfully updated!'
  end

  def destroy
    @medication.destroy
    redirect_to medications_path, notice: 'Medication successfully deleted!'
  end

  private
  def create_medication_notification(message)
    notification = Notification.new(message: message, recipient_id: current_user.id)

    if notification.save
      NotificationBroadcastJob.perform_later("notification_channel_#{current_user.id}", current_user.id, message)
    else
      handle_notification_creation_error(notification)
    end
  end








  def handle_notification_creation_error(notification)
    flash[:alert] = "Notification couldn't be saved: #{notification.errors.full_messages.join(', ')}"
    Rails.logger.error(flash[:alert])
  end


  def schedule_medication_notification(medication, message)
    notification_time = medication.start_time
    NotificationBroadcastJob.set(wait_until: notification_time).perform_later("notification_channel_#{current_user.id}", current_user.id, message)
  end





  def set_medication
    @medication = current_user.medications.find(params[:id])
  end

  def medication_params
    params.require(:medication).permit(
      :name,
      :med_type,
      :quantity,
      :instruction,
      :frequency,
      :start_time,
      :interval_id,
      :start_date,
      :end_date
    )
  end
end

app/views/medications/_frequency_display.html.erb
<!-- <% if medication.frequency %>
  <p><strong>Frequency:</strong> <%= medication.frequency.name %></p>
<% else %>
  <p><strong>Frequency:</strong> Not specified</p>
<% end %> -->

app/views/medications/_frequency_form.html.erb
<!-- <%= simple_form_for medication, url: medication_path(medication), method: :patch do |f| %>
  <%#= f.input :frequency_id, collection: frequencies, label_method: :name, value_method: :id, prompt: 'Select a Frequency', input_html: { class: 'form-control' } %>
  <%#= f.button :submit, "Update Frequency", class: 'btn btn-primary' %>
<% end %> -->

app/views/medications/congrats.html.erb
<div class="d-flex flex-column align-items-center justify-content-center text-center">
  <h1 class="mb-3">Congratulations!</h1>
  <p class="mb-4">You have successfully added a new medication.</p>

  <%= link_to 'Back to medications', medications_path, class: 'btn btn-primary btn-lg mr-3' %>
</div>

app/views/medications/destroy.html.erb
<!-- destroy.html.erb -->
<!-- <h1>Delete Medication</h1> -->
<!-- <p>Are you sure you want to delete this medication?</p> -->
<%#= button_to 'Yes', medication_path ( @medication), method: :delete, data: { confirm: 'Are you sure?' }, title: 'Delete' %>
<%#= button_to 'No', medications_path, title: 'Back', class: "btn btn-primary", method: :get %> <!-- This will create a primary back button -->

app/views/medications/edit.html.erb
<body class="medication-page">
  <!-- <div class="container mb-5 edit-medication-form"> -->
    <%= simple_form_for @medication, url: medication_path(@medication), method: :patch, html: { class: 'row g-3  p-4 rounded shadow' } do |f| %>
    <h1 class="mb-4 text-left medication-title">Edit Medication</h1>

    <div class="form-group row">
      <%= f.input :name, label: 'Medication Name:', input_html: { class: 'form-control col-12 col-md-6 mb-3', placeholder: 'Enter medication name' } %>
    </div>

    <div class="form-group row">
      <%= f.input :med_type, label: 'Med Type:', collection: ['Tablets', 'Capsules','Drops','Inhalers','Injections','Liquid','Topical medecines','Suppositories'], prompt: 'Select Medication Type', input_html: { class: 'form-control col-12 col-md-6 mb-3', placeholder: 'Select medication type' } %>
    </div>

    <div class="form-group row">
      <%= f.input :quantity, label: 'Quantity:', input_html: { min: 1, max: 100, value: @medication.quantity, class: 'form-control col-12 col-md-6 mb-3', placeholder: 'Enter quantity' } %>
    </div>

    <div class="form-group row">
      <%= f.input :instruction, label: 'Instruction:', collection: ['Before meal', 'After meal'], prompt: 'Select Instruction', input_html: { class: 'form-control col-12 col-md-6 mb-3', placeholder: 'Select instruction' } %>
    </div>

    <div class="form-group row">
      <%= f.input :frequency, label: 'Frequency:', collection: ['Once per day', 'Twice per day', 'Thrice per day'], prompt: 'Select Frequency', input_html: { class: 'form-control col-12 col-md-6 mb-3', placeholder: 'Select frequency' } %>
    </div>

    <div class="form-group row">
      <label for="start-time" class="col-12 col-md-6">Start Time:</label>
      <div class="input-group col-12 col-md-6 mb-3">
        <%= f.time_select :start_time, {}, id: 'start-time', class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.association :interval, label: 'Interval:', collection: Interval.all, prompt: 'Select Interval', input_html: { class: 'form-control col-12 col-md-6 mb-3',id: 'interval_select', placeholder: 'Select interval' } %>
    </div>

    <div class="form-field row">
      <div class="start-date-field col-12 col-md-6 mb-3">
        <%= f.label :start_date %>
        <%= f.date_field :start_date, placeholder: 'Enter start date' %>
      </div>

      <div class="end-date-field col-12 col-md-6 mb-3">
        <%= f.label :end_date %>
        <%= f.date_field :end_date, placeholder: 'Enter end date' %>
      </div>
    </div>

    <div class="form-actions row">
      <div class="col-12 col-md-12 mb-3 d-flex justify-content-left">
      <%= f.button :submit, "Update", class: 'btn  mr-2 btn-edit' %>
      <%= link_to 'Back', medication_path(@medication), class: 'btn btn-secondary-margin-left btn-edit' %>
    </div>
  <% end %>
<!-- </div> -->
</body>

app/views/medications/index.html.erb
<body class="body-index">
  <div class="container">
    <div class="content">
      <div class="filter-meds" role="group" aria-label="Filter Medications">
        <%= link_to 'All', medications_path, class: 'btn btn-secondary index' %>
        <%= link_to 'Today', medications_path(filter: 'today'), class: 'btn btn-secondary index' %>
        <%= link_to 'Tomorrow', medications_path(filter: 'tomorrow'), class: 'btn btn-secondary index' %>
      </div>

      <% if @notifications.present? && @notifications.respond_to?(:each) %>
  <% @notifications.each do |notification| %>
    <% unless notification.read? %>
      <div class="alert alert-info">
        <%= notification.message %>
      </div>
    <% end %>
  <% end %>
<% end %>



      <div class="date-index">
        <% if @date %>
          <p><%= @date %></p>
        <% end %>
      </div>

      <div class="meds-c">
        <% if @medications.present? %>
          <% @medications.reverse.each do |medication| %>
            <div class="rectangle-medi SlideDown">
              <a href="<%= medication_path(medication) %>" class="medication-link">
                <img src="https://i.ibb.co/1Rx7HYZ/pngwing-com-2.png" alt="pngwing-com-2" class="medication-image">
                <div class="medication-info">
                  <h5 class="medication-name"><%= medication.name %></h5>
                  <p class="medication-type"><%= medication.med_type %></p>
                </div>
              </a>
            </div>
          <% end %>
        <% else %>
          <p>No medications found.</p>
        <% end %>
      </div>
    </div>
  </div>

<script>
  document.addEventListener("DOMContentLoaded", function() {

   // Function to display notifications
function displayNotifications(notifications) {
  const notificationsContainer = document.getElementById('notificationsContainer');

  if (!notificationsContainer) {
    console.error('Notifications container not found!');
    return;
  }

  // Clear existing notifications
  notificationsContainer.innerHTML = '';

  // Check if notifications is an array before iterating
  if (Array.isArray(notifications)) {
    // Iterate through notifications and append to the container
    notifications.forEach(notification => {
      if (!isNotificationDisplayed(notification.id)) {
        const notificationCard = createNotificationCard(notification);
        notificationsContainer.appendChild(notificationCard);
        markNotificationAsDisplayed(notification.id);
      }
    });
  } else {
    console.error('Invalid or null notifications array.');
  }
}


    // Function to create a notification card
    function createNotificationCard(notification) {
      const card = document.createElement('div');
      card.classList.add('notification-card');

      const message = document.createElement('p');
      message.textContent = notification.message;
      card.appendChild(message);

      // Add an <audio> element for the notification sound
    //  const audio = document.createElement('audio');
// audio.src = '.app/assets/images/sound.mp3';
// audio.autoplay = true; // Keep autoplay set to true
// card.appendChild(audio);


      const closeButton = document.createElement('button');
      closeButton.textContent = 'Close';
      closeButton.classList.add('close-notification'); // Add a class for event delegation
      closeButton.dataset.notificationId = notification.id; // Set the notification ID as a data attribute
      closeButton.addEventListener('click', () => {
        card.remove();
        deleteNotification(notification.id); // Call the function to delete the notification
        unmarkNotificationAsDisplayed(notification.id);
      });
      card.appendChild(closeButton);

      return card;
    }

   // Function to calculate the time difference and fetch notifications accordingly
    function calculateTimeDifference(medicationStartTime) {
      const currentTime = new Date();
      const timeDifference = medicationStartTime - currentTime;

      if (timeDifference > 0) {
        console.log('Time difference:', timeDifference);

        // Set a timeout to fetch notifications when the time difference becomes zero
        setTimeout(() => fetchNotifications(), Math.max(timeDifference, 1000)); // Minimum timeout of 1000 milliseconds
      } else {
        console.log('Medication start time has already passed.');
      }
    }

    // Function to fetch notifications
    function fetchNotifications() {
      console.log('Fetching notifications...');
      fetch('/notifications')
        .then(response => response.json())
        .then(data => {
          console.log('Fetched notifications:', data);
          displayNotifications(data);
        })
        .catch(error => console.error('Error fetching notifications:', error));
    }

    // Function to delete a notification via AJAX
    function deleteNotification(notificationId) {
      fetch(`/notifications/${notificationId}`, {
        method: 'DELETE',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': Rails.csrfToken(), // Include the CSRF token
        },
      })
        .then(response => {
          if (!response.ok) {
            throw new Error(`Error deleting notification: ${response.statusText}`);
          }
          console.log('Notification deleted successfully.');
        })
        .catch(error => console.error(error));
    }

    // Function to check if a notification has been displayed
    function isNotificationDisplayed(notificationId) {
      const displayedNotifications = getDisplayedNotifications();
      return displayedNotifications.includes(notificationId);
    }

    // Function to mark a notification as displayed
    function markNotificationAsDisplayed(notificationId) {
      const displayedNotifications = getDisplayedNotifications();
      displayedNotifications.push(notificationId);
      setDisplayedNotifications(displayedNotifications);
    }

    // Function to unmark a notification as displayed
    function unmarkNotificationAsDisplayed(notificationId) {
      const displayedNotifications = getDisplayedNotifications();
      const index = displayedNotifications.indexOf(notificationId);
      if (index !== -1) {
        displayedNotifications.splice(index, 1);
        setDisplayedNotifications(displayedNotifications);
      }
    }

    // Function to get displayed notifications from local storage
    function getDisplayedNotifications() {
      const displayedNotificationsJSON = localStorage.getItem('displayedNotifications');
      return displayedNotificationsJSON ? JSON.parse(displayedNotificationsJSON) : [];
    }

    // Function to set displayed notifications in local storage
    function setDisplayedNotifications(displayedNotifications) {
      const displayedNotificationsJSON = JSON.stringify(displayedNotifications);
      localStorage.setItem('displayedNotifications', displayedNotificationsJSON);
    }

    // Assuming medicationStartTimes is an array of start times sent from your Rails view
    const medicationStartTimes =
      [
        <% if user_signed_in? && !@medications.nil? %>
        <% @medications.each do |medication| %>
        new Date('<%= medication.start_time %>'),
        <% end %>
        <% end %>
      ];

    // Calculate time differences for each medication
    medicationStartTimes?.forEach(medicationStartTime => {
      calculateTimeDifference(medicationStartTime);
    });
  });
</script>




</body>

app/views/medications/new.html.erb
<body class="body-new">
<!-- <div class="container mb-5"> -->
  <%= simple_form_for @medication, html: { class: 'medication-form' } do |f| %>
  <h2 class="form-title h2new"><strong>Add Medication</strong></h2>
    <div class="form-group row">
      <%= f.input :name, label: '<b>Medication Name:</b>'.html_safe, input_html: { class: 'form-control col-12 col-md-6 mb-3', placeholder: 'Enter medication name' } %>
    </div>
    <div class="form-group row">
      <%= f.input :med_type, label: '<b>Med Type:</b>'.html_safe, collection: ['Tablets', 'Capsules','Drops','Inhalers','Injections','Liquid','Topical medecines','Suppositories'], prompt: 'Select Medication Type', input_html: { class: 'form-control col-12 col-md-6 mb-3', placeholder: 'Select medication type' } %>
    </div>
    <div class="form-group row">
      <%= f.input :quantity, label: '<b>Quantity:</b>'.html_safe, input_html: { min: 1, max: 100, value: '', class: 'form-control col-12 col-md-6 mb-3', placeholder: 'Enter quantity' } %>
    </div>
    <div class="form-group row">
      <%= f.input :instruction, label: '<b>Instruction:</b>'.html_safe, collection: ['Before meal', 'After meal'], prompt: 'Select Instruction', input_html: { class: 'form-control col-12 col-md-6 mb-3', placeholder: 'Select instruction' } %>
    </div>
    <div class="form-group row">
      <%= f.input :frequency, label: '<b>Frequency:</b>'.html_safe, collection: ['Once per day', 'Twice per day', 'Thrice per day'], prompt: 'Select Frequency', input_html: { class: 'form-control col-12 col-md-6 mb-3', placeholder: 'Select frequency' } %>
    </div>
    <div class="form-group row">
      <label for="start-time" class="col-12 col-md-6"><strong>Start Time:</strong></label>
      <div class="input-group col-12 col-md-6 mb-3">
        <%= f.time_select :start_time, {}, id: 'start-time', class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.association :interval, label: '<b>Interval:</b>'.html_safe, collection: Interval.all, prompt: 'Select Interval', input_html: { class: 'form-control col-12 col-md-6 mb-3',id: 'interval_select', placeholder: 'Select interval' } %>
    </div>
    <div class="form-field row">
      <div class="start-date-field col-12 col-md-6 mb-3">
        <%= f.label :start_date, '<b>Start Date: </b>'.html_safe %>
        <%= f.date_field :start_date, placeholder: 'Enter start date' %>
      </div>
      <div class="end-date-field col-12 col-md-6 mb-3">
        <%= f.label :end_date, '<b>End Date: </b>'.html_safe %>
        <%= f.date_field :end_date, placeholder: 'Enter end date' %>
      </div>
    </div>

    <div class="form-actions row">
      <div class="col-12 col-md-12 mb-3 d-flex justify-content-left">
        <%= f.button :submit, 'Save', class: 'btn mr-2 btn-new' %>
        <%= link_to 'Back', medications_path, class: 'btn btn-new' %>
      </div>
    </div>
  <% end %>
<!-- </div> -->
</body>

app/views/medications/set_duration.html.erb
<!-- <h1>Set Medication Duration</h1>

<%= simple_form_for @medication, url: set_duration_medication_path(@medication), method: :patch do |f| %>
  <%# <%= f.input :start_date, label: 'Start Date', as: :date, start_year: Date.today.year, end_year: Date.today.year + 10, placeholder: { year: 'Select Year', month: 'Select Month', day: 'Select Day' }, value: nil %> %>
  <%# <%= f.input :end_date, label: 'End Date', as: :date, start_year: Date.today.year, end_year: Date.today.year + 10, placeholder: { year: 'Select Year', month: 'Select Month', day: 'Select Day' }, value: nil %> %>
   <%= f.input :start_date, as: :date_select %>
  <%= f.input :end_date, as: :date_select %>
  <%= f.button :submit, 'Save', class: 'btn btn-primary' %>
  <%= link_to 'Back', dashboards_path, class: 'btn btn-secondary' %>
<% end %> -->

app/views/medications/show.html.erb
<body class="body-gradient">
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card mb-3 card-gradient slideDown card-border">
          <div class="card-header text-white">
            <h1><%= @medication.name %></h1>
          </div>
          <div class="card-body">
            <% if @medication.frequency %>
              <!-- <p><strong>Name:</strong> <%= @medication.name %></p> -->
              <p><strong>Start Date:</strong> <%= @medication.start_date.strftime("%B %d, %Y") %></p>
              <p><strong>End Date:</strong> <%= @medication.end_date.strftime("%B %d, %Y") %></p>
              <p><strong>Start time:</strong> <%=@medication.start_time.strftime("%H:%M")%></p>
              <p><strong>Medication Type:</strong> <%= @medication.med_type %></p>
              <p><strong>Duration:</strong> <%= @medication.duration %> days</p>
              <p><strong>Quantity:</strong> <%= @medication.quantity %></p>
              <p><strong>Frequency:</strong> <%= @medication.frequency %></p>
              <p><strong>Instruction:</strong> <%= @medication.instruction %></p>
              <p><strong>Interval:</strong> <%= @medication.interval.name %></p>

            <% else %>
              <p><strong>Frequency:</strong> Not specified</p>
            <% end %>
          </div>
          <div class="card-footer transparent-bg d-flex justify-content-center">

            <%= link_to edit_medication_path(@medication), class: 'btn btn-show' do %>
            <i class="fas fa-edit"></i> Edit
          <% end %>

          <%= link_to @medication, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-delete btn-show' do %>
            <i class="fas fa-trash-alt"></i> Delete
          <% end %>

          <%= link_to medications_path, class: 'btn  btn-show' do %>
            <i class="fas fa-arrow-left"></i> Back
          <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</body>