config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # devise_for :users, controllers: { registrations: 'profiles' }
  mount Sidekiq::Web => '/sidekiq'
  root to: "pages#home"
  devise_for :users
  resources :medications
  get '/notifications', to: 'notifications#index'
  delete '/notifications', to: 'notifications#destroy_all'




resources :notifications, only: [:destroy]

  # resources :reminders, only: [:index, :show, :edit, :update, :destroy] do
  #   member do
  #     patch :mark_as_taken
  #   end
  # end

  resources :intervals, only: [:index, :show, :create, :update, :destroy]
  resources :medication_frequencies, only: [:index, :show, :create, :update, :destroy]
  resource :profile, only: [:show]

  devise_scope :user do
    resources :sessions, only: [:destroy], path: 'users/sign_out', as: :destroy_user_session
  end






end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  include Noticed::Model
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :medications
  has_many :notifications, as: :recipient
  # has_many :notifications, dependent: :destroy
  # has_one :recipient
  # belongs_to :recipient, optional: true
  attribute :user_type, :string
  attribute :scheduled_medication_time, :time

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container-footer">
  <div class="tabbar tab-style5">
    <ul class="flex-center">
      <li id="home-tab" class="home active" data-where="home"><span class="material-icons-outlined">medication</span></li>
      <li id="add-tab" class="about" data-where="add"><span class="material-icons-outlined">add</span></li>
      <li id="user-tab" class="help" data-where="user"><span class="material-icons-outlined">person</span></li>
    </ul>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const footerButtons = document.querySelectorAll(".container-footer button");

    document.addEventListener("click", function (event) {
      const target = event.target;
      const isVisible = footerButtons[0].style.transform === "translateY(0%)";
      const isFooterButton = Array.from(footerButtons).some(button => button.contains(target));

      if (isFooterButton) {
        return;
      }

      footerButtons.forEach(button => {
        button.style.transform = isVisible ? "translateY(100%)" : "translateY(0%)";
      });
    });

    const homeTab = document.getElementById("home-tab");
    const addTab = document.getElementById("add-tab");
    const userTab = document.getElementById("user-tab");

    homeTab.addEventListener("click", function () {
      setTimeout(function () {
        window.location.href = "<%= medications_path %>";
      }, 300);
    });

    addTab.addEventListener("click", function () {
      setTimeout(function () {
        window.location.href = "<%= new_medication_path %>";
      }, 300);
    });

    userTab.addEventListener("click", function () {
      setTimeout(function () {
        window.location.href = "<%= profile_path %>";
      }, 300);
    });

    const uls = document.querySelectorAll("ul");

    uls.forEach((ul) => {
      const resetClass = ul.parentNode.getAttribute("class");
      const lis = ul.querySelectorAll("li");

      lis.forEach((li) => {
        li.addEventListener("click", (e) => {
          e.preventDefault();
          e.stopPropagation();
          const target = e.currentTarget;

          if (
            target.classList.contains("active") ||
            target.classList.contains("follow")
          ) {
            return;
          }

          ul.parentNode.setAttribute(
            "class",
            `${resetClass} ${target.getAttribute("data-where")}-style`
          );

          lis.forEach((item) => clearClass(item, "active"));

          setClass(target, "active");
        });
      });
    });

    function clearClass(node, className) {
      node.classList.remove(className);
    }

    function setClass(node, className) {
      node.classList.add(className);
    }

    const icons = document.querySelectorAll(".material-icons-outlined");

    icons.forEach((icon) => {
      icon.addEventListener("click", function () {
        icon.style.transition = "transform 0.3s ease-in-out";
        icon.style.transform = "translateY(-10px)";

        setTimeout(function () {
          icon.style.transform = "translateY(0px)";
        }, 300);
      });
    });
  });
</script>

app/views/shared/_medication_card.html.erb
<div class="rectangle-medi">
  <a href="<%= medication_path(medication) %>" class="medication-link">
    <img src="https://i.ibb.co/1Rx7HYZ/pngwing-com-2.png" alt="pngwing-com-2" class="medication-image">
    <div class="medication-info">
      <h5><%= medication.name %></h5>
      <p><%= medication.med_type %></p>
    </div>
  </a>
  <!-- Checkbox at the right end of the medication card -->
  <div class="red-checkbox-container">
    <%= check_box_tag "medication_ids[]", medication.id, false, class: "red-checkbox", data: { remote: true } %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to image_tag("https://kitt.lewagon.com/placeholder/users/jtaurah", class: "avatar", alt: "avatar"), profile_path %>
<% if @user %>
  <div class="hello-msg"> <h2>Hello, <%= @user.name %></h2></div>
<% end %>

 <img src="https://i.ibb.co/0hnFzHs/logo-white-removebg-preview-1.png" alt="Your Image" class="navbar-img-small">

</div>



  </div>
</div>

app/views/shared/_notification.html.erb
<% if @notifications.present? && @notifications.respond_to?(:each) %>
  <% @notifications.each do |notification| %>
    <% unless notification.read? %>
      <div class="alert alert-info">
        <%= notification.message %>
      </div>
    <% end %>
  <% end %>
<% end %>